/**
 * Configuration Manager for Console Application
 * Handles .env file management and configuration loading
 */

import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';

export class Config {
  constructor() {
    this.envPath = path.join(process.cwd(), '.env');
    this.config = {};
    this.isLoaded = false;
  }

  /**
   * Check if .env file exists
   */
  async envFileExists() {
    try {
      await fs.access(this.envPath);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Load configuration from .env file
   */
  async load() {
    try {
      const exists = await this.envFileExists();
      
      if (exists) {
        const content = await fs.readFile(this.envPath, 'utf-8');
        this.config = dotenv.parse(content);
        
        // Also load into process.env
        dotenv.config({ path: this.envPath });
      }
      
      this.isLoaded = true;
      return this.config;
    } catch (error) {
      throw new Error(`Failed to load configuration: ${error.message}`);
    }
  }

  /**
   * Get a configuration value
   */
  get(key, defaultValue = null) {
    return process.env[key] || this.config[key] || defaultValue;
  }

  /**
   * Set a configuration value (in memory only)
   */
  set(key, value) {
    this.config[key] = value;
    process.env[key] = value;
  }

  /**
   * Save configuration to .env file
   */
  async save(configData = null) {
    const dataToSave = configData || this.config;
    
    // Build .env content
    const lines = [
      '# ITFY E-Voting Backend Configuration',
      `# Generated by Admin Console on ${new Date().toISOString()}`,
      '',
      '# ================================',
      '# Server Configuration',
      '# ================================',
      `NODE_ENV=${dataToSave.NODE_ENV || 'development'}`,
      `PORT=${dataToSave.PORT || '3000'}`,
      `CORS_ORIGIN=${dataToSave.CORS_ORIGIN || '*'}`,
      '',
      '# ================================',
      '# Database Configuration',
      '# ================================',
      `MONGODB_URI=${dataToSave.MONGODB_URI || 'mongodb://localhost:27017/itfy-evoting'}`,
      `DB_MAX_RETRIES=${dataToSave.DB_MAX_RETRIES || '5'}`,
      `DB_RETRY_DELAY_MS=${dataToSave.DB_RETRY_DELAY_MS || '5000'}`,
      '',
      '# ================================',
      '# Redis/Cache Configuration',
      '# ================================',
      `REDIS_URL=${dataToSave.REDIS_URL || 'redis://localhost:6379'}`,
      `REDIS_MAX_RETRIES=${dataToSave.REDIS_MAX_RETRIES || '5'}`,
      `REDIS_RETRY_DELAY_MS=${dataToSave.REDIS_RETRY_DELAY_MS || '2000'}`,
      '',
      '# ================================',
      '# JWT Configuration',
      '# ================================',
      `JWT_SECRET=${dataToSave.JWT_SECRET || this.generateSecret()}`,
      `JWT_REFRESH_SECRET=${dataToSave.JWT_REFRESH_SECRET || this.generateSecret()}`,
      `JWT_EXPIRATION=${dataToSave.JWT_EXPIRATION || '15m'}`,
      `JWT_REFRESH_EXPIRATION=${dataToSave.JWT_REFRESH_EXPIRATION || '7d'}`,
      '',
      '# ================================',
      '# Email Configuration',
      '# ================================',
      `EMAIL_HOST=${dataToSave.EMAIL_HOST || 'smtp.gmail.com'}`,
      `EMAIL_PORT=${dataToSave.EMAIL_PORT || '587'}`,
      `EMAIL_USER=${dataToSave.EMAIL_USER || ''}`,
      `EMAIL_PASS=${dataToSave.EMAIL_PASS || ''}`,
      `EMAIL_FROM=${dataToSave.EMAIL_FROM || 'noreply@itfy-evoting.com'}`,
      '',
      '# ================================',
      '# Frontend Configuration',
      '# ================================',
      `FRONTEND_URL=${dataToSave.FRONTEND_URL || 'http://localhost:3001'}`,
      '',
      '# ================================',
      '# Payment Configuration (Optional)',
      '# ================================',
      `PAYSTACK_SECRET_KEY=${dataToSave.PAYSTACK_SECRET_KEY || ''}`,
      `PAYSTACK_PUBLIC_KEY=${dataToSave.PAYSTACK_PUBLIC_KEY || ''}`,
      '',
      '# ================================',
      '# File Upload Configuration',
      '# ================================',
      `UPLOAD_DIR=${dataToSave.UPLOAD_DIR || './uploads'}`,
      `MAX_FILE_SIZE=${dataToSave.MAX_FILE_SIZE || '10485760'}`,
      '',
      '# ================================',
      '# Console Configuration',
      '# ================================',
      `CONSOLE_SETUP_COMPLETE=${dataToSave.CONSOLE_SETUP_COMPLETE || 'true'}`,
    ];

    const content = lines.join('\n');
    await fs.writeFile(this.envPath, content, 'utf-8');
    
    // Reload configuration
    await this.load();
    
    return true;
  }

  /**
   * Generate a random secret key
   */
  generateSecret(length = 64) {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*()_+-=[]{}|;:,.<>?';
    let result = '';
    for (let i = 0; i < length; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }

  /**
   * Get all configuration as object
   */
  getAll() {
    return { ...this.config };
  }

  /**
   * Update a single value in .env file
   */
  async updateValue(key, value) {
    this.config[key] = value;
    await this.save();
    return true;
  }

  /**
   * Validate required configuration
   */
  validateRequired() {
    const required = [
      'MONGODB_URI',
      'JWT_SECRET',
    ];

    const missing = required.filter(key => !this.get(key));
    
    if (missing.length > 0) {
      return {
        valid: false,
        missing
      };
    }

    return { valid: true, missing: [] };
  }

  /**
   * Get configuration summary
   */
  getSummary() {
    return {
      server: {
        nodeEnv: this.get('NODE_ENV', 'development'),
        port: this.get('PORT', '3000'),
        corsOrigin: this.get('CORS_ORIGIN', '*'),
      },
      database: {
        uri: this.maskSensitive(this.get('MONGODB_URI', '')),
        connected: false,
      },
      cache: {
        url: this.maskSensitive(this.get('REDIS_URL', '')),
        connected: false,
      },
      jwt: {
        configured: !!this.get('JWT_SECRET'),
        expiration: this.get('JWT_EXPIRATION', '15m'),
      },
      email: {
        configured: !!this.get('EMAIL_USER') && !!this.get('EMAIL_PASS'),
        host: this.get('EMAIL_HOST', 'smtp.gmail.com'),
      },
      frontend: {
        url: this.get('FRONTEND_URL', 'http://localhost:3001'),
      }
    };
  }

  /**
   * Mask sensitive information
   */
  maskSensitive(value) {
    if (!value) return '(not configured)';
    
    // Mask password in URIs
    return value.replace(/\/\/[^:]+:[^@]+@/, '//***:***@');
  }
}
